[WCNCR00166482] misc: Fix compilation error caused by 64-bit integer division
[Description]
Fix compilation error caused by 64-bit integer division

Call div_u64() to do unsigned 64-bit integer division for
both 64-bit and 32-bit Linux system compatibility.

Or the error will show in 32-bit Linux while inserting module:
 wlan_mt6632_usb: Unknown symbol __udivdi3 (err 0)

Change-Id: I4b9c15cc8e41156727a7169ce02f88bad3cb8952
Signed-off-by: Awk Jiang <awk.jiang@mediatek.com>
CR-Id: WCNCR00166482
Feature: misc
Reviewed-on: http://gerrit.mediatek.inc:8080/1267430
CheckPatch: Check Patch <srv_checkpatch@mediatek.com>
Reviewed-by: George Kuo <george.kuo@mediatek.com>
Reviewed-by: Deren Wu <deren.wu@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>